### ISSUE TITLE
Movidius

### ISSUE THREAD

**Issue by 3073** [PINTO0309/MobileNet-SSD#3]
I get my movidius ncs from amazon right now and i need to use it for fast computing ability.
model : ssd mobilenet
framework: caffe

please show me how to  get the ncs work with my pi...
 I have installed the NCS SDK on my raspberry pi before I received my movidius from amazon carrier using the below link:
dependencies like opencv and tensorflow are also installed by default based on the link:
https://github.com/movidius/ncsdk

**Comment by PINTO0309** [comment]
@3073 
First of all, i need to confirm to you the following.

1.Is NCSDK 2.05.xx.xx installed? "$ git clone -b ncsdk2 http://github.com/Movidius/ncsdk"
2.Is protobuf version 3.5.1? "$ protoc --version"
3.Is tensorflow version 1.9.0?
4.Is NCAPPZOO done git clone already? "$ git clone -b ncsdk2 https://github.com/movidius/ncappzoo.git"

NCAPPZOO is a sample program repository of NCS.
Experience, it will not work properly unless upgraded to tensorflow 1.8.0 or 1.9.0.

**Comment by 3073** [comment]
here is the confirmation for your question.
1. I  installed NCSDK 1.x  " git clone https://github.com/movidius/ncsdk.git " . it is version 1
2. when I write "protoc --version" on the terminal of RPI , it gives me 3.0.0
3. tensorflow version is 1.7 it is installed by default when version 1 NCS SDK is installed
Thank you

**Comment by PINTO0309** [comment]
@3073 
OK.
The sample programs of NCSDK v1.0 and v2.0 are not completely compatible.
For your environment, please download the program for v1.0 first.

v1.0
https://github.com/movidius/ncappzoo.git
https://github.com/PINTO0309/MobileNet-SSD/tree/v1.0
https://github.com/PINTO0309/MobileNet-SSD-RealSense/tree/v1.0

v2.0
https://github.com/movidius/ncappzoo/tree/ncsdk2
https://github.com/PINTO0309/MobileNet-SSD.git
https://github.com/PINTO0309/MobileNet-SSD-RealSense

I recommend you read the README firmly.
All you have to do is insert the stick into the USB port and execute it.

A sample of the command to generate a graph file from the Caffe model is shown below.
``
$ mvNCCompile aaa.prototxt -w bbb.caffemodel -s 12
``

**Comment by 3073** [comment]
Thank you. as I understand the procedure  is:
1.  I first install NCS SDK on my pi 
2. then Install NCS SDK  ( the same version like what is installed on my pi) on my laptop 
3. generate graph file using the trained model weight and prototxt files (for caffe model)  on my laptop
4. move the graph file and other pyhton file to the RPI 
5. insert the Movidius on the USB port of the RPI and execute the code
6. then have fun with the accelerated computing of Movidius
please correct me 
thank you again

**Comment by PINTO0309** [comment]
@3073 
That's right!
All flows look correctly.

**Comment by 3073** [comment]
Thanks bro ... thanks for real ....

**Comment by 3073** [comment]
git clone https://github.com/movidius/ncsdk.git 
does not work . I think the repository is closed temporarly. 
Do you know any other link for cloning ncsdk ?

**Comment by PINTO0309** [comment]
@3073 
First of all, I recommend that you check the NCS Forum.
https://ncsforum.movidius.com/discussion/1053/ncsdk-on-github-is-going-opensource-current-software-releases-moved-temporarily

**Comment by 3073** [comment]
[Error 7] Toolkit Error: USB Failure. Code: No devices found

what do you think this error is for when " make examples" is executed on
the terminal?

**Comment by 3073** [comment]
frequently it gives a sound like when a flash is inserted in a computer ;
connection and disconnection sound.
 may be USB port is not compatible? but still make install is running with
the error [Error 7] Toolkit Error: USB Failure. Code: No devices found

**Comment by 3073** [comment]
make examples. sorry

**Comment by PINTO0309** [comment]
@3073 

https://ncsforum.movidius.com/search?Search=make+examples
https://ncsforum.movidius.com/search?Search=virtualbox
https://ncsforum.movidius.com/discussion/948/procedure-for-make-examples-ncsdk-v2-05-00-02-raspberrypi3-raspbian-stretch-ubuntu16-04#latest

Is there one stick?
Are you using "USB Hub"?
Are you using Virtualbox?

**Comment by 3073** [comment]
1. yes I am using one movidius device ( if you mean that)
2. no I directly connected the movidius stick to the usb port of my computer
3. yes I am using virtualbox (ubuntu 16.04 installed)

by the way kepping the error I just proceed and run make examples and
finally generate the graph file. but when I try to connect the movidius to
the RPI the detection speed is like the previous...may be i have to install
latest version of SDK.

**Comment by PINTO0309** [comment]
@3073 
OK.
Intel admits that using Virtualbox has problems.
Long ago, I succeeded in running Virtualbox with NCSDK 1.12.xx, but there are only articles in Japanese.
If you really want to try it with Virtualbox, please carefully read the English articles I presented earlier.

>but when I try to connect the movidius to the RPI the detection speed is like the previous...

Are you using the program of my Github repository?

**Comment by 3073** [comment]
Thank you for real
 no I am using a program of my own.
ok let me dig for some time and came back

**Comment by 3073** [comment]
I just proceed with the error I told you before ( [Error 7] Toolkit Error:
USB Failure. Code: No devices found)
and generate the graph file (with no error; I do not know if that is normal
with the " no devices found error").
and when I try to execute a file on my Pi it throws the following error.
AttributeError: 'module' object has no attribute 'Enumerate_devices'
  do you think I should install ubuntu along side windows instead of using
virtualbox for ubuntu installation will fix the problem?
what about installing version two SDK ?

**Comment by PINTO0309** [comment]
@3073 
I am taking a nap and I got up now.
Japan is now 17: 00.
>AttributeError: 'module' object has no attribute 'Enumerate_devices'

You Installed → NCSDK v2.05.xx
Probably, Your smaple program version →  NCSDK v1.12.xx
Since NCSDK v2.05 has greatly changed API specifications, errors are displayed.

>do you think I should install ubuntu along side windows instead of using
virtualbox for ubuntu installation will fix the problem?

It is not recommended to use Virtualbox so that it is unstable and slow in operation.

>what about installing version two SDK ?

That is probably the correct answer.

**Comment by PINTO0309** [comment]
@3073 
Sorry.
You Installed → NCSDK v2.05.xx
Probably, Your smaple program version → NCSDK v1.12.xx

**Comment by 3073** [comment]
Ethiopia is now 6 ( in the middle of the day).
by the way Asians are smart in electronics...
by the way how do you know whether a program is ncsdk version 1 or 2?
do you mean mean if I installed version 1 NCSDK on my laptop to generate
graph file, that graph file is of the version 1. Therefore to use the graph
in Pi for detection with movidius, I should have install NCSDK version 1 on
my Pi  because the graph is generated in a  version 1 NCSDK installed pc?

**Comment by PINTO0309** [comment]
@3073 

>by the way how do you know whether a program is ncsdk version 1 or 2?

You need to see a part of the program.
It distinguis between uppercase and lowercase letters.
For example,

v2.xx.xx program
https://github.com/PINTO0309/MobileNet-SSD/blob/v2.0/MultiStickSSD.py
```
mvnc.global_set_option(mvnc.GlobalOption.RW_LOG_LEVEL, 2)
devices = mvnc.enumerate_devices()
```

v1.xx.xx program
https://github.com/PINTO0309/MobileNet-SSD/blob/v1.0/MultiStickSSD.py
```
mvnc.SetGlobalOption(mvnc.GlobalOption.LOG_LEVEL, 2)
devices = mvnc.EnumerateDevices()
```

>do you mean mean if I installed version 1 NCSDK on my laptop to generate
>graph file, that graph file is of the version 1. Therefore to use the graph
>in Pi for detection with movidius, I should have install NCSDK version 1 on
>my Pi  because the graph is generated in a  version 1 NCSDK installed pc?

Now, the program you are trying to run with RaspberryPi is compatible with NCSDK v1.
However, looking at the error message, RaspberryPi seems to have NCSDK v2 installed.

Recommended steps (1)
```
Your Ubuntu PC:
1. Uninstall NCSDK v1
2. Install NCSDK v2
3. Make graph file by NCSDK v2
4. Copy graph file to RaspberryPi

Your RaspberryPi:
1. Create a sample program for v2.
2. Sample Program execution.
```

Or below.

Recommended steps (2)
```
Your Ubuntu PC:
1. Make graph file by NCSDK v1
2. Copy graph file to RaspberryPi

Your RaspberryPi:
1. Uninstall NCSDK v2
2. Install NCSDK v1
3. Create a sample program for v1.
4. Sample Program execution.
```

**Comment by 3073** [comment]
. thank you guys
I will be into it....
Caffe, tesorflow will be installed by default in NCSDK v2?

**Comment by 3073** [comment]
how to uninstall NCSDK?
make clean will work?

**Comment by PINTO0309** [comment]
@3073 

>Caffe, tesorflow will be installed by default in NCSDK v2?

Yes.
But there are notes.
Tesorflow 1.7.0 installed by default is very unstable.
I recommend that you uninstall it once and then install tensorflow 1.9.0.
```
$ sudo pip3 uninstall tensorflow
$ sudo apt install libatlas-base-dev
$ sudo pip3 install tensorflow
```

>how to uninstall NCSDDK?

```
$ cd ~/ncsdk
$ make uninstall
```

**Comment by 3073** [comment]
the most interesting part of you is you never try to blame for asking you
many times.....
 thank you bro..... I get it

**Comment by 3073** [comment]
I am not lucky with this tiny device bro. I should have switch off
from the virtual machine and try it on ubuntu by installing ubuntu
alongside my windows 7 laptop.

it throws error in make examples

****** WARNING: using empty weights ******

**Comment by PINTO0309** [comment]
@3073 
I will reply to tomorrow.
Because it is 2 am now.
But please tell me the following.
1. Will not the situation change when I insert and remove Stick once?
2. Can you post the full text of "make examples"?

Good night...

**Comment by 3073** [comment]
ame@ame-VirtualBox:~/Downloads/ncsdk-2.05.00.02$ make examples
./install-opencv.sh
OpenCV Installation Starting
Reading installer configuration variables from ./ncsdk.conf
Installing opencv python for non-Raspbian
Collecting opencv-python>=3.4.0.12
  Using cached
https://files.pythonhosted.org/packages/6a/c8/32023281fc27b787f966a33b8ae946b0f3491062e8b1f1e48029f0269a0d/opencv_python-3.4.2.17-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.11.1 in
/usr/local/lib/python3.5/dist-packages (from opencv-python>=3.4.0.12)
Installing collected packages: opencv-python
Successfully installed opencv-python-3.4.2.17
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting opencv-contrib-python>=3.4.0.12
  Using cached
https://files.pythonhosted.org/packages/af/8d/982e0d670dcaa588242d4889814c09b137fbc62bc57df9fbf490ab6c9b24/opencv_contrib_python-3.4.2.17-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.11.1 in
/usr/local/lib/python3.5/dist-packages (from
opencv-contrib-python>=3.4.0.12)
Installing collected packages: opencv-contrib-python
Successfully installed opencv-contrib-python-3.4.2.17
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting opencv-python>=3.4.0.12
  Using cached
https://files.pythonhosted.org/packages/60/6a/dcc146a95bc8bde469958ee3ae693a8721798c5f9da7ea58e5a580754610/opencv_python-3.4.2.17-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.11.1 in
/usr/local/lib/python2.7/dist-packages (from opencv-python>=3.4.0.12)
Installing collected packages: opencv-python
Successfully installed opencv-python-3.4.2.17
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting opencv-contrib-python>=3.4.0.12
  Using cached
https://files.pythonhosted.org/packages/8c/6a/e7e6328cad323e0b39a9d72a24906341f1593b1c67b985e2d422bc335e37/opencv_contrib_python-3.4.2.17-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.11.1 in
/usr/local/lib/python2.7/dist-packages (from
opencv-contrib-python>=3.4.0.12)
Installing collected packages: opencv-contrib-python
Successfully installed opencv-contrib-python-3.4.2.17
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
OpenCV Installation Finished

make examples starting.
(cd examples; make)
make[1]: Entering directory '/home/ame/Downloads/ncsdk-2.05.00.02/examples'
make -C apps/.
make[2]: Entering directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/apps'
make -C hello_ncs_py/.
make[3]: Entering directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/apps/hello_ncs_py'
nothing to make, use 'make run' to run.
make[3]: Leaving directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/apps/hello_ncs_py'
make -C multistick_cpp/.
make[3]: Entering directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/apps/multistick_cpp'

making googlenet
(cd ../../caffe/GoogLeNet; make compile; cd ../../apps/multistick_cpp; cp
../../caffe/GoogLeNet/graph ./googlenet.graph;)
make[4]: Entering directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/caffe/GoogLeNet'

making prereqs
(cd ../../data/ilsvrc12; make)
make[5]: Entering directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/data/ilsvrc12'
make[5]: Leaving directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/data/ilsvrc12'

making prototxt
Prototxt file already exists

making caffemodel
caffemodel file already exists

making compile
mvNCCompile -w bvlc_googlenet.caffemodel -s 12 deploy.prototxt
/usr/local/bin/ncsdk/Controllers/Parsers/TensorFlowParser/Convolution.py:44:
SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(False, "Layer type not supported by Convolution: " + obj.type)
mvNCCompile v02.00, Copyright @ Intel Corporation 2017

Layer  inception_3b/1x1  forced to im2col_v2, because its output is used in
concat
/usr/local/bin/ncsdk/Controllers/FileIO.py:65: UserWarning: You are using a
large type. Consider reducing your data sizes for best performance
Blob generated
make[4]: Leaving directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/caffe/GoogLeNet'

making squeezenet
(cd ../../caffe/SqueezeNet; make compile; cd ../../apps/multistick_cpp; cp
../../caffe/SqueezeNet/graph ./squeezenet.graph;)
make[4]: Entering directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/caffe/SqueezeNet'

making prereqs
(cd ../../data/ilsvrc12; make)
make[5]: Entering directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/data/ilsvrc12'
make[5]: Leaving directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/data/ilsvrc12'
LICENSE file already exists

making prototxt
Prototxt file already exists

making caffemodel
caffemodel file already exists

making compile
mvNCCompile -w squeezenet_v1.0.caffemodel -s 12 deploy.prototxt
/usr/local/bin/ncsdk/Controllers/Parsers/TensorFlowParser/Convolution.py:44:
SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(False, "Layer type not supported by Convolution: " + obj.type)
mvNCCompile v02.00, Copyright @ Intel Corporation 2017

/usr/local/bin/ncsdk/Controllers/FileIO.py:65: UserWarning: You are using a
large type. Consider reducing your data sizes for best performance
Blob generated
make[4]: Leaving directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/caffe/SqueezeNet'

making multistick_cpp
cp googlenet.graph cpp/googlenet.graph;
cp squeezenet.graph cpp/squeezenet.graph;
g++ cpp/multistick.cpp -o cpp/multistick_cpp -lmvnc
Created cpp/multistick_cpp executable
make[3]: Leaving directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/apps/multistick_cpp'
make -C hello_ncs_cpp/.
make[3]: Entering directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/apps/hello_ncs_cpp'

making hello_ncs_cpp
g++ cpp/hello_ncs.cpp -o cpp/hello_ncs_cpp -lmvnc
Created cpp/hello_ncs_cpp executable
make[3]: Leaving directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/apps/hello_ncs_cpp'
make[2]: Leaving directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/apps'
make -C caffe/.
make[2]: Entering directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/caffe'
make -C AlexNet
make[3]: Entering directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/caffe/AlexNet'

making prereqs
(cd ../../data/ilsvrc12; make)
make[4]: Entering directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/data/ilsvrc12'
make[4]: Leaving directory
'/home/ame/Downloads/ncsdk-2.05.00.02/examples/data/ilsvrc12'
chmod +x run.py

making prototxt
Prototxt file already exists

making profile
mvNCProfile deploy.prototxt -s 12
/usr/local/bin/ncsdk/Controllers/Parsers/TensorFlowParser/Convolution.py:44:
SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(False, "Layer type not supported by Convolution: " + obj.type)
mvNCProfile v02.00, Copyright @ Intel Corporation 2017

****** WARNING: using empty weights ******
/usr/local/bin/ncsdk/Controllers/FileIO.py:65: UserWarning: You are using a
large type. Consider reducing your data sizes for best performance
Blob generated
USB: Transferring Data...
E: [         0] dispatcherEventReceive:200 dispatcherEventReceive() Read
failed -9

E: [         0] dispatcherEventSend:738 Write failed -9

E: [         0] dispatcherEventSend:730 Write failed -4

**Comment by 3073** [comment]
the device name in the USB setting change from movidius Ltd movidius
MA2X5X  to intel corporation VSP loopback device itself.

**Comment by PINTO0309** [comment]
@3073 
It's a typical problem with Virtualbox.
The NCS Forum has reported that the behavior of the USB port is wrong.
Please try the following first.

1. USB 1.1 Controller OHCI
2. USB 2.0 Controller EHCI
3. USB 3.0 Controller XHCI

https://ncsforum.movidius.com/discussion/comment/3023/#Comment_3023

Virtualbox is not really recommended.
Note that the main sequence of "make examples" is almost over, so you can safely ignore it as it is.
If you do not need a sample program.

**Comment by 3073** [comment]
I installed ubuntu alongside with windows ( instead of virtual box) and
install NCSDK V2 on both the Pi and Ubuntu. but
  AttributeError: 'module' object has no attribute 'EnumerateDevices'
is still alive

**Comment by 3073** [comment]
normally I take the weight files from other repo to generate the graph. then I use my own program to execute based on that graph....I think it is normal.

**Comment by PINTO0309** [comment]
@3073 

>AttributeError: 'module' object has no attribute 'EnumerateDevices' is still alive

You are running the **NCSDK v1** sample program.
I do not know what program, but need to rewrite to **v2 sample program**.
Please take a closer look at **Recommended steps (1)**.
It is correct that the error is displayed now.
If you absolutely want to run the v1 program, it is **Recommended steps (2)**.

Or, a program that simulates the v1 program on v2 is published in ncappzoo, so please try it.

**◆ncapi2_shim**
**Contains a shim python file that allows NCAPI v1 applications run with an installation of NCAPI v2.
To use the shim do the following to your existing NCAPI v1 program.**
https://github.com/movidius/ncappzoo/tree/ncsdk2/ncapi2_shim

**Comment by PINTO0309** [comment]
@3073 
**◆Migration**
https://movidius.github.io/ncsdk/ncapi/python_api_migration.html

**Comment by 3073** [comment]
https://www.pyimagesearch.com/2018/02/19/real-time-object-detection-on-the-raspberry-pi-with-the-movidius-ncs/

I am using the code in this link to test movidius. yes it is version
one......whcih line bring the errror? because I have seen for version 2 is
also the same some other place.

**Comment by PINTO0309** [comment]
@3073 
Because it is troublesome to explain, can you use this sample?
By the way, it works faster than "pyimagesearch" sample.
It is a sample of v2 and It works with usb camera.
RealSense is unnecessary.

https://github.com/PINTO0309/MobileNet-SSD-RealSense

**◆USB Camera Mode**
```
$ sudo raspi-config
"7.Advanced Options" - "A7 GL Driver" - "G3 Legacy"
$ cd ~/MobileNet-SSD-RealSense
$ python3 MultiStickSSDwithRealSense.py -mod 1 -wd 640 -ht 480
```

Please replace the graph file with the one you created with confidence.

**Comment by 3073** [comment]
Last time i installed SDK on the pi without problem. but now I am unable to
install it . it goes up to 55% and stuck for long time. I am using the
links in the link below.
https://github.com/movidius/ncsdk

but the SDK link is down and I used the alternative they give.

**Comment by PINTO0309** [comment]
@3073 
The points are below.

Extension of the SWAP area is absolutely necessary.
It will hang up if not specified.
```
$ sudo nano /etc/dphys-swapfile

CONF_SWAPSIZE=100
↓
CONF_SWAPSIZE=2048

$ sudo /etc/init.d/dphys-swapfile restart swapon -s
```

And, "-j1" is necessary.
It will hang up if not specified.

```
$ make -j1
```

**Comment by 3073** [comment]
things seem fine now with the ncs. but cv2.videocapture is not
working. may be there is an error in opencv while make examples?

**Comment by PINTO0309** [comment]
@3073 
As I always say, can you trap errors with Try - Except etc?
What is the error message displayed?

**Comment by 3073** [comment]
no error.                                 vs = videoCapture(0)
 while true:   retval,frame = vs.read() then frame is always none and
retval is always false.

**Comment by PINTO0309** [comment]
@3073 
Please post the full text of the following command.
```
$ sudo ls /dev/video*
```

**Comment by 3073** [comment]
it works! i download the same new video and it works for the new one.

**Comment by PINTO0309** [comment]
@3073 
I do not know what happened, but congratulations.
I think that I will solve earlier if you ask questions to Adrian of pyimagesearch.
I do not want to preach, originally, posts unrelated to the repository are violations of manners.

By the way, a girl 's baby was born on the last day of your last issue.

Please close "issue" if you calm down.

**Comment by 3073** [comment]
Hi.  sorry for the late reply.  Internet  connection was down in my faculty.

By the way I need to be honest with you... i agree that messages unrelated
to the repo may have problems based on the terms of conditions.  but I have
seen a good personality in you and I believe that you will solve my problem
and you did it !!! Thank you for that...
Normally I Know that I am a little bit retarded in understanding but that
is because I am  Mechanical engineering professional with no know  of
computer science. I am studying it right now by my self.
so now I would like to beg your permission for asking you  questions
about raspberry pi and Movidius NCS  either on this repo or by any
means of communication.
 at last I do not understand what do you means by the following quote
in your previous message?
I think that I will solve earlier if you ask questions to Adrian of
pyimagesearch.
I will close this issue immediately as soon as you reply to this message

**Comment by PINTO0309** [comment]
@3073 
Good morning.
I am not angry, so do not worry.
Rather, I feel that your "issue" will be of help to other engineers.
Actually, I majored in economics.
Computer science is not specialized.
I just touch the device with my hobbies.

>I think that I will solve earlier if you ask questions to Adrian of pyimagesearch.

I think that the sample program you had a problem was a program listed in "pyimage search".
Is not it wrong?
The blog administrator of "pyimage search" is a person named Adrian.
Also, it seems that a bulletin board is prepared for "pyimage search".
Regarding the program that Adrian himself created, I thought that asking Adrian questions would solve the problem quickly.
