### ISSUE TITLE
training a model

### ISSUE THREAD

**Issue by 3073** [PINTO0309/MobileNet-SSD#4]
Hi my friend
I used  to  tested a model using  somebody's trained prototxt and caffemodel  caffe model files.. but it skip the detection of the object and even sometimes it does not detect at all. but it worked for the person who provide it  with the same video file....
do you think i should have trained (fine tune it)..
so could you show me how should I train the caffe model for a my  dataset.
i need to detect a person.....

**Comment by PINTO0309** [comment]
@3073 
Let's organize one by one.

> but it skip the detection of the object and even sometimes it does not detect at all.

First of all, please adjust the "threshould" number in program.

For example)
threshould = 0.80 → 0.45 → 0.30 → 0.25 → ...
thresh = 0.7 → 0.3 .→ ...
min_score_percent = 0.8 → 0.7 → 0.6 → 0.5 → ...

"Threshold(min_score_percent )" means the threshold of probability of being "human".

**Comment by 3073** [comment]
I am using a threshold of 0.6

**Comment by PINTO0309** [comment]
@3073 
Please change to 0.2

**Comment by 3073** [comment]
Thanks
but that  cause another object   considered as a person....

**Comment by PINTO0309** [comment]
@3073 
I think you noticed.
If threshould is lowered, extra objects are detected, raising threshould will decrease the detection rate.
You need to decide on reasonable "threshould" yourself.
If you are not satisfied with any "threshould", It is necessary to re-train the model or review the model itself.
First of all, please try looking for yourself whether there is no satisfying "threshould".
The important thing is not to ask for perfection.

**Comment by 3073** [comment]
it works  for a threshold of 0.25... but as i said it detect any other
object as person and at threshold of 0.45 it works fine....
thanks .... but still i need to train it for person...  because i  need to
know it ..... so if you have time please show me.....

**Comment by PINTO0309** [comment]
@3073 
I do not mean to confuse you.
I got your time a little to find out what you understand.

OK.
For details on how to train model yourself, please see below.
It is written in my "Readme" from the beginning, so please read it carefully.

https://github.com/PINTO0309/MobileNet-SSD-RealSense#construction-of-learning-environment-and-simple-test-for-model-ubuntu1604-x86_64-pc--gpunvidia-geforce

or 

https://github.com/avBuffer/MobilenetSSD_caffe

**Comment by PINTO0309** [comment]
@3073 
One month passed since the last answer.
Since there seems to be no particular problem, I will close "issue" once.
