### ISSUE TITLE
Latest SDK (2.08) support

### ISSUE THREAD

**Issue by yinguobing** [PINTO0309/MobileNet-SSD#5]
Hi Pinto,

Great work!
Looks like Movidius has released a latest [NVSDK v2.08.01](https://github.com/movidius/ncsdk/releases/tag/v2.08.01.02). I found this version of SDK does not support the graph file included in your repo, 
Error messages:

```
W: [         0] checkGraphMonitorResponse:931	Graph monitor request returned error
W: [         0] ncGraphAllocate:1125	The device didn't accept the graph

W: [         0] ncGraphAllocate:1128	graph file version is incompatible

Traceback (most recent call last):
  File "MultiStickSSD.py", line 44, in <module>
    graphHandle.append(graph[devnum].allocate_with_fifos(devHandle[devnum], graph_buffer))
  File "/home/pi/.local/lib/python3.5/site-packages/mvnc/mvncapi.py", line 613, in allocate_with_fifos
    raise Exception(Status(status))
Exception: Status.UNSUPPORTED_GRAPH_FILE
```

I tried using the graph file compiled localy from `/home/pi/Desktop/ncappzoo/caffe/SSD_MobileNet`, however, the detection result is always 1 result with class name tvmonitor and a bounding box of whole frame size.

As you have successfully run the SSD model before, would you please try the latest NVSDK and update this repo if possible?

Thanks!

**Comment by PINTO0309** [comment]
@yinguobing 
I did not do anything special, but regenerated the graph file and committed it.
It compiled with NCSDK v2.08.01.
In addition to "tvmonitor" it seems that "person" also recognizes normally.

By the way, the following repositories have better performance.
**https://github.com/PINTO0309/MobileNet-SSD-RealSense.git**

**Comment by yinguobing** [comment]
Great! The new graph file works. Also I will try the other repository later. 
Thanks!
