### ISSUE TITLE
OpenCV installation error

### ISSUE THREAD

**Issue by thakkarmitul** [PINTO0309/MobileNet-SSD#6]
Traceback (most recent call last):
  File "MultiStickSSD.py", line 12, in <module>
    import cv2
  File "/home/pi/.local/lib/python3.5/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libQtGui.so.4: cannot open shared object file: No such file or directory

import cv2 works with python 2 but it doesn't work with python 3.

**Comment by PINTO0309** [comment]
@thakkarmitul
Please try below.
```
$ sudo apt-get install libqtgui4
```

**Comment by thakkarmitul** [comment]
Not working...Even tried to install from scratch. 

pi@raspberrypi:~ $ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.5/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libQtTest.so.4: cannot open shared object file: No such file or directory

**Comment by PINTO0309** [comment]
@thakkarmitul 
Please try below.
Probably, Your Python3 environment is not normal.
```
$ sudo apt-get install libqt4-test
```

**Comment by thakkarmitul** [comment]
Finally, it worked! I installed opencv python 3 and then installed ncs. 
Thank you!
